# Generated by Django 3.2.6 on 2021-08-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loveapp_2', '0005_auto_20210813_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='age',
            new_name='나이',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='내용',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='gender',
            new_name='성별',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='number',
            new_name='연애_횟수',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author_name',
            new_name='작성자',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='job',
            new_name='직업',
        ),
    ]
