# Generated by Django 3.2.6 on 2021-08-13 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loveapp_3', '0004_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='내용',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='나이',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='성별',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='연애_횟수',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='작성자',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='직업',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='love',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='love',
            name='author_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='love',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='love',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='love',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='author_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='loveapp_3.love'),
        ),
    ]
